# Generated by Django 4.1.2 on 2022-10-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to='')),
                ('ImageKey', models.CharField(max_length=255)),
                ('PassWordProtected', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('UploaderCountry', models.CharField(max_length=255)),
                ('UploadingTime', models.CharField(max_length=255)),
            ],
        ),
    ]
