# Generated by Django 4.1.2 on 2022-10-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uselesslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UselessList',
        ),
    ]
