# Generated by Django 4.1.2 on 2022-10-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_uselesslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelist',
            old_name='ImageKey',
            new_name='ImageName',
        ),
    ]
