# Generated by Django 4.1.2 on 2022-10-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_imagekey_imagelist_imagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelist',
            old_name='ImageName',
            new_name='ImageKey',
        ),
    ]
