# Generated by Django 4.1.2 on 2022-10-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_imagename_imagelist_imagekey'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryImageViewKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageURL', models.CharField(max_length=255)),
                ('ImageKey', models.CharField(max_length=255)),
                ('IP', models.CharField(max_length=255)),
                ('RegisteredTime', models.CharField(max_length=255)),
            ],
        ),
    ]
